DROP TABLE IF EXISTS BanUser;
CREATE TABLE BanUser(
	userId INT,
	reason VARCHAR(255),
	dateBanned TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	dateUnbanned TIMESTAMP NOT NULL,
	PRIMARY KEY(userId),
	CONSTRAINT fk_banuser_user
		FOREIGN KEY(userId) 
		REFERENCES User(userId)
		ON DELETE CASCADE
);